version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROJECT=${PROJECT}
      - REGION=${REGION}
      - INSTANCE_NAME=${INSTANCE_NAME}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - $HOME/.config/gcloud:/root/.config/gcloud

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

