version: '3.8'

services:
  backend:
    build: .
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME:-triptide}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-postgres}
      - JWT_SECRET=${JWT_SECRET}
      # GCP Cloud SQL variables
      - PROJECT=${PROJECT}
      - REGION=${REGION}
      - INSTANCE_NAME=${INSTANCE_NAME}
      # Mail configuration
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - ${HOME}/.config/gcloud:/root/.config/gcloud:ro
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME:-triptide}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

