spring:
  application:
    name: triptide-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      additional-paths: src/main/java/
    livereload:
      enabled: true
  
  thymeleaf:
    cache: false
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-specific-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  mvc:
    contentnegotiation:
      defaultContentType: application/json
  
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: "your-256-bit-secret-key-here-make-it-long-and-secure"
  expiration: 86400000  # 24 hours in milliseconds