spring:
  application:
    name: ${APP_NAME:triptide-backend}
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/triptide}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  devtools:
    restart:
      enabled: ${DEVTOOLS_ENABLED:true}
      poll-interval: ${DEVTOOLS_POLL_INTERVAL:2s}
      quiet-period: ${DEVTOOLS_QUIET_PERIOD:1s}
      additional-paths: src/main/java/
    livereload:
      enabled: ${LIVERELOAD_ENABLED:true}
  
  thymeleaf:
    cache: false
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-specific-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  mvc:
    contentnegotiation:
      defaultContentType: application/json
  
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${PORT:8080}
  tomcat:
    accesslog:
      enabled: true

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-make-it-long-and-secure}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

logging:
  level:
    org.springframework: INFO
    org.apache.tomcat: DEBUG
    org.apache.catalina: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true