spring:
  application:
    name: ${APP_NAME:triptide-backend}

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://db:5432/${DBNAME}
    username: ${DBUSER}
    password: ${DBPASS}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql:///${DBNAME}?cloudSqlInstance=${PROJECT}:${REGION}:${INSTANCE_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: ${DBUSER}
    password: ${DBPASS}

---
# Common configuration for all profiles
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
